### PR TITLE
Fix parsing identifiers that snake_case to keywords

### LINKED ISSUE #18: Bitfield Specifier enum cannot have a variant called "In"
```rust
// src/lib.rs
use modular_bitfield::prelude::*;

#[derive(BitfieldSpecifier)]
enum Fails {
    Foo = 0,
    Bar = 1,
    In = 2,
    Out = 3
}
```
```sh
$ rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
$ cargo build
   Compiling example v0.1.0 (/tmp/example)
error: expected pattern, found keyword `in`
 --> src/lib.rs:3:10
  |
3 | #[derive(BitfieldSpecifier)]
  |          ^^^^^^^^^^^^^^^^^ expected pattern
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc-macro derive produced unparseable tokens
 --> src/lib.rs:3:10
  |
3 | #[derive(BitfieldSpecifier)]
  |          ^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: could not compile `example`.
```
```
$ rustc --version
rustc 1.48.0-nightly (d006f5734 2020-08-28)
$ RUSTFLAGS='-Z macro-backtrace' cargo build
   Compiling example v0.1.0 (/tmp/example)
error: expected pattern, found keyword `in`
   --> src/lib.rs:3:10
    |
3   |   #[derive(BitfieldSpecifier)]
    |            ^^^^^^^^^^^^^^^^^
    |            |
    |            expected pattern
    |            in this macro invocation
    |
   ::: /home/qyriad/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/modular-bitfield-impl-0.6.0/src/lib.rs:98:1
    |
98  | / pub fn bitfield_specifier(input: TokenStream) -> TokenStream {
99  | |     bitfield_specifier::generate(input.into()).into()
100 | | }
    | |_- in this expansion of `#[derive(BitfieldSpecifier)]`

error: proc-macro derive produced unparseable tokens
 --> src/lib.rs:3:10
  |
3 | #[derive(BitfieldSpecifier)]
  |          ^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: could not compile `example`.
```

This happens if it's typed as `In` or `IN`, but `r#in` and most curiously `iN` *do* work (but `r#In` and `r#IN` do not).

### PR DESCRIPTION
**Pull request by Qyriad**
Fixes #18.

### CODE REVIEW

File: impl/src/bitfield_specifier.rs [hunk 1]
```diff
@@ -79,8 +80,12 @@ pub fn generate3(input: syn::ItemEnum) -> syn::Result<TokenStream2> {
...
         });
         use heck::SnakeCase as _;
-        use crate::ident_ext::IdentExt as _;
-        let snake_variant = syn::Ident::from_str(&variant.to_string().to_snake_case());
+        let snake_variant = &variant.to_string().to_snake_case();
+        let snake_variant = match syn::parse_str::<syn::Ident>(snake_variant) {
+            Ok(parsed_ident) => parsed_ident,
+            // Use a raw identifier to allow strict keywords.
+            Err(_) => format_ident!("r#{}", snake_variant)
+        };
```
Comment (Robbepop) [inline impl/src/bitfield_specifier.rs:88]: nice approach!

**Review by Robbepop — APPROVED** [review]
Wish I had implemented some CI earlier to be more confident in merging but looks good to me.

**Comment by Robbepop** [comment]
Thank you for the fix!
